version: '3.7'

services:
  app:
    image: 'registry.makasim.com/gogame:latest'
    working_dir: '/app'
    environment:
      - "FLOWSTATESRV_HTTP_HOST=http://flowstatesrv:8282"
    networks:
      - 'external'
      - 'default'
    depends_on:
      - 'flowstatesrv'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8181"
        - "traefik.frontend.rule=Host:gogame.makasim.com"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"

  flowstatesrv:
    image: 'registry.makasim.com/flowstatesrv:a309c7b6'
    environment:
        - "FLOWSTATESRV_ADDR=0.0.0.0:8282"
        - "CORS_ENABLED=true"
    networks:
      - 'external'
      - 'default'
    ports:
      - '8282:8282'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8282"
        - "traefik.frontend.rule=Host:flowstate.makasim.com"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"

networks:
  external:
    external:
      name: 'traefik'
