version: '3'

tasks:
  genproto:
    cmds:
      - buf lint
      - rm -rf protogen/* ui/src/gen/*
      - buf generate

  build:
    cmds:
      - |
        cd ui
        pnpm i
        pnpm build
        
      - |
        go mod tidy && go mod vendor
        GOOS=linux GOARCH=amd64 go build -o gogame main/main.go
      - |
        COMMIT=$(git rev-list -1 HEAD | cut -c1-8)
        echo "Building gogame:$COMMIT"
        docker build --platform="linux/amd64" -t "gogame:$COMMIT" .
    env:
      VITE_API_URL: "https://gogame.makasim.com/"
  push:
    cmds:
      - |
        COMMIT=$(git rev-list -1 HEAD | cut -c1-8)
        docker tag "gogame:$COMMIT" "registry.makasim.com/gogame:$COMMIT"
        docker tag "gogame:$COMMIT" "registry.makasim.com/gogame:latest"
        echo "Pushing registry.makasim.com/gogame:$COMMIT"
        docker push "registry.makasim.com/gogame:$COMMIT"
        echo "Pushing registry.makasim.com/gogame:latest"
        docker push "registry.makasim.com/gogame:latest"

  deploy:
    cmds:
      - |
        ssh "root@gogame.makasim.com" "mkdir -p /gogame"
        scp "docker-compose.deploy.yml" "root@gogame.makasim.com:/gogame"
        ssh "root@gogame.makasim.com" "docker stack deploy --with-registry-auth --compose-file /gogame/docker-compose.deploy.yml gogame"
