version: '3'

tasks:
  genproto:
    cmds:
      - buf lint
      - rm -rf protogen/* ui/src/gen/*
      - buf generate

  build:
    cmds:
      - |
        cd ui
        pnpm i
        pnpm build

      - |
        go mod tidy && go mod vendor
        GOOS=linux GOARCH=arm64 go build -o gogame ./main/
        
        VERSION="$(git rev-list -1 HEAD | cut -c1-8)"
        if [ -n "$(git diff)" ]; then
          VERSION="${VERSION}-$(git diff | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        if [ -n "$(git diff --cached)" ]; then
          VERSION="${VERSION}-$(git diff --cached | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        echo "Building gogmae:$VERSION"
        docker build --platform="linux/arm64" -t "gogmae:$VERSION" .
    env:
      VITE_API_URL: '{{ default "https://gogame.makasim.com/" .VITE_API_URL }}'

  push:
    cmds:
      - |
        VERSION="$(git rev-list -1 HEAD | cut -c1-8)"
        if [ -n "$(git diff)" ]; then
          VERSION="${VERSION}-$(git diff | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        if [ -n "$(git diff --cached)" ]; then
          VERSION="${VERSION}-$(git diff --cached | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        
        docker tag "gogmae:$VERSION" "registry2.makasim.com/gogame:$VERSION"
        echo "Pushing registry2.makasim.com/gogame:$VERSION"
        docker push "registry2.makasim.com/gogame:$VERSION"

  deploy:
    cmds:
      - |
        VERSION="$(git rev-list -1 HEAD | cut -c1-8)"
        if [ -n "$(git diff)" ]; then
          VERSION="${VERSION}-$(git diff | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        if [ -n "$(git diff --cached)" ]; then
        VERSION="${VERSION}-$(git diff --cached | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        cp "deployment.yaml" "deployment.tmp.yaml"
        env VERSION="$VERSION" envsubst < "deployment.yaml" > "deployment.tmp.yaml"
        
        kubectl -n gogame apply -f "deployment.tmp.yaml"