// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: gogame/v2/server.proto

package gogamev2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_BLACK       Color = 1
	Color_COLOR_WHITE       Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_BLACK",
		2: "COLOR_WHITE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_BLACK":       1,
		"COLOR_WHITE":       2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_gogame_v2_server_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_gogame_v2_server_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Change:
	//
	//	*Change_Move_
	//	*Change_Pass_
	//	*Change_Undo_
	//	*Change_End_
	Change isChange_Change `protobuf_oneof:"change"`
}

func (x *Change) Reset() {
	*x = Change{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{1}
}

func (m *Change) GetChange() isChange_Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func (x *Change) GetMove() *Change_Move {
	if x, ok := x.GetChange().(*Change_Move_); ok {
		return x.Move
	}
	return nil
}

func (x *Change) GetPass() *Change_Pass {
	if x, ok := x.GetChange().(*Change_Pass_); ok {
		return x.Pass
	}
	return nil
}

func (x *Change) GetUndo() *Change_Undo {
	if x, ok := x.GetChange().(*Change_Undo_); ok {
		return x.Undo
	}
	return nil
}

func (x *Change) GetEnd() *Change_End {
	if x, ok := x.GetChange().(*Change_End_); ok {
		return x.End
	}
	return nil
}

type isChange_Change interface {
	isChange_Change()
}

type Change_Move_ struct {
	Move *Change_Move `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type Change_Pass_ struct {
	Pass *Change_Pass `protobuf:"bytes,2,opt,name=pass,proto3,oneof"`
}

type Change_Undo_ struct {
	Undo *Change_Undo `protobuf:"bytes,3,opt,name=undo,proto3,oneof"`
}

type Change_End_ struct {
	End *Change_End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Change_Move_) isChange_Change() {}

func (*Change_Pass_) isChange_Change() {}

func (*Change_Undo_) isChange_Change() {}

func (*Change_End_) isChange_Change() {}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rev     int32     `protobuf:"varint,2,opt,name=rev,proto3" json:"rev,omitempty"`
	Name    string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Player1 *Player   `protobuf:"bytes,4,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2 *Player   `protobuf:"bytes,5,opt,name=player2,proto3" json:"player2,omitempty"`
	Changes []*Change `protobuf:"bytes,8,rep,name=changes,proto3" json:"changes,omitempty"`
	Board   *Board    `protobuf:"bytes,11,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetRev() int32 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *Game) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *Game) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *Game) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colors []Color `protobuf:"varint,1,rep,packed,name=colors,proto3,enum=gogame.v2.Color" json:"colors,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Rows []*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{4}
}

func (x *Board) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Board) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Player1 *Player `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type JoinGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string  `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Player2 *Player `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinGameRequest) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

type JoinGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{8}
}

func (x *JoinGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type StreamGamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamGamesRequest) Reset() {
	*x = StreamGamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGamesRequest) ProtoMessage() {}

func (x *StreamGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGamesRequest.ProtoReflect.Descriptor instead.
func (*StreamGamesRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{9}
}

type StreamGamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *StreamGamesResponse) Reset() {
	*x = StreamGamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGamesResponse) ProtoMessage() {}

func (x *StreamGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGamesResponse.ProtoReflect.Descriptor instead.
func (*StreamGamesResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{10}
}

func (x *StreamGamesResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{11}
}

func (x *StreamEventsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{12}
}

func (x *StreamEventsResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev  int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MoveX    int32  `protobuf:"varint,4,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	MoveY    int32  `protobuf:"varint,5,opt,name=move_y,json=moveY,proto3" json:"move_y,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{13}
}

func (x *MoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MoveRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *MoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveRequest) GetMoveX() int32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *MoveRequest) GetMoveY() int32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{14}
}

func (x *MoveResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type PassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev  int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *PassRequest) Reset() {
	*x = PassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRequest) ProtoMessage() {}

func (x *PassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRequest.ProtoReflect.Descriptor instead.
func (*PassRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{15}
}

func (x *PassRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PassRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *PassRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *PassResponse) Reset() {
	*x = PassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassResponse) ProtoMessage() {}

func (x *PassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassResponse.ProtoReflect.Descriptor instead.
func (*PassResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{16}
}

func (x *PassResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type UndoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev  int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accept   bool   `protobuf:"varint,4,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *UndoRequest) Reset() {
	*x = UndoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRequest) ProtoMessage() {}

func (x *UndoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRequest.ProtoReflect.Descriptor instead.
func (*UndoRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{17}
}

func (x *UndoRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UndoRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *UndoRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UndoRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type UndoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *UndoResponse) Reset() {
	*x = UndoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoResponse) ProtoMessage() {}

func (x *UndoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoResponse.ProtoReflect.Descriptor instead.
func (*UndoResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{18}
}

func (x *UndoResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ResignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *ResignRequest) Reset() {
	*x = ResignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignRequest) ProtoMessage() {}

func (x *ResignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignRequest.ProtoReflect.Descriptor instead.
func (*ResignRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{19}
}

func (x *ResignRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ResignRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ResignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *ResignResponse) Reset() {
	*x = ResignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignResponse) ProtoMessage() {}

func (x *ResignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignResponse.ProtoReflect.Descriptor instead.
func (*ResignResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{20}
}

func (x *ResignResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type Change_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId       string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color          Color  `protobuf:"varint,2,opt,name=color,proto3,enum=gogame.v2.Color" json:"color,omitempty"`
	X              int32  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	CapturedStones int32  `protobuf:"varint,5,opt,name=captured_stones,json=capturedStones,proto3" json:"captured_stones,omitempty"`
}

func (x *Change_Move) Reset() {
	*x = Change_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change_Move) ProtoMessage() {}

func (x *Change_Move) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change_Move.ProtoReflect.Descriptor instead.
func (*Change_Move) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Change_Move) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Change_Move) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Change_Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Change_Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Change_Move) GetCapturedStones() int32 {
	if x != nil {
		return x.CapturedStones
	}
	return 0
}

type Change_Pass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *Change_Pass) Reset() {
	*x = Change_Pass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change_Pass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change_Pass) ProtoMessage() {}

func (x *Change_Pass) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change_Pass.ProtoReflect.Descriptor instead.
func (*Change_Pass) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Change_Pass) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type Change_Undo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *Change_Undo) Reset() {
	*x = Change_Undo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change_Undo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change_Undo) ProtoMessage() {}

func (x *Change_Undo) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change_Undo.ProtoReflect.Descriptor instead.
func (*Change_Undo) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Change_Undo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Change_Undo) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type Change_End struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Draw   bool    `protobuf:"varint,3,opt,name=draw,proto3" json:"draw,omitempty"`
	Winner *Player `protobuf:"bytes,9,opt,name=winner,proto3" json:"winner,omitempty"`
	WonBy  string  `protobuf:"bytes,10,opt,name=won_by,json=wonBy,proto3" json:"won_by,omitempty"`
}

func (x *Change_End) Reset() {
	*x = Change_End{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v2_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change_End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change_End) ProtoMessage() {}

func (x *Change_End) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v2_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change_End.ProtoReflect.Descriptor instead.
func (*Change_End) Descriptor() ([]byte, []int) {
	return file_gogame_v2_server_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Change_End) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

func (x *Change_End) GetWinner() *Player {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *Change_End) GetWonBy() string {
	if x != nil {
		return x.WonBy
	}
	return ""
}

var File_gogame_v2_server_proto protoreflect.FileDescriptor

var file_gogame_v2_server_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x32, 0x22, 0x2c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x9d, 0x04, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x04,
	0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x73,
	0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x75, 0x6e, 0x64, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x48, 0x00,
	0x52, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x12, 0x29, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6e,
	0x64, 0x1a, 0x90, 0x01, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x53, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x23, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x3f, 0x0a, 0x04, 0x55, 0x6e, 0x64,
	0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x1a, 0x5b, 0x0a, 0x03, 0x45, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x64, 0x72, 0x61, 0x77, 0x12, 0x29, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x32, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x15, 0x0a, 0x06, 0x77, 0x6f, 0x6e, 0x5f, 0x62, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x77, 0x6f, 0x6e, 0x42, 0x79, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x22, 0xeb, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x76, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x2b, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22,
	0x2f, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73,
	0x22, 0x3f, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x22, 0x54, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x22, 0x39, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x22, 0x57, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2b,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x22, 0x37, 0x0a, 0x10, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x13, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x59, 0x22, 0x33, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x76, 0x0a, 0x0b,
	0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x22, 0x33, 0x0a, 0x0c, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x35, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x2a, 0x40, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4c, 0x4f, 0x52,
	0x5f, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4c, 0x4f,
	0x52, 0x5f, 0x57, 0x48, 0x49, 0x54, 0x45, 0x10, 0x02, 0x32, 0xf3, 0x01, 0x0a, 0x0b, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x32,
	0xd4, 0x02, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x53, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x61, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x55,
	0x6e, 0x64, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x98, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x32, 0x42, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6b, 0x61, 0x73, 0x69, 0x6d, 0x2f, 0x67, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x2f, 0x76, 0x32, 0x3b, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x76, 0x32, 0xa2, 0x02,
	0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x32,
	0xca, 0x02, 0x09, 0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x15, 0x47,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x3a, 0x3a, 0x56,
	0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gogame_v2_server_proto_rawDescOnce sync.Once
	file_gogame_v2_server_proto_rawDescData = file_gogame_v2_server_proto_rawDesc
)

func file_gogame_v2_server_proto_rawDescGZIP() []byte {
	file_gogame_v2_server_proto_rawDescOnce.Do(func() {
		file_gogame_v2_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_gogame_v2_server_proto_rawDescData)
	})
	return file_gogame_v2_server_proto_rawDescData
}

var file_gogame_v2_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gogame_v2_server_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_gogame_v2_server_proto_goTypes = []any{
	(Color)(0),                   // 0: gogame.v2.Color
	(*Player)(nil),               // 1: gogame.v2.Player
	(*Change)(nil),               // 2: gogame.v2.Change
	(*Game)(nil),                 // 3: gogame.v2.Game
	(*Row)(nil),                  // 4: gogame.v2.Row
	(*Board)(nil),                // 5: gogame.v2.Board
	(*CreateGameRequest)(nil),    // 6: gogame.v2.CreateGameRequest
	(*CreateGameResponse)(nil),   // 7: gogame.v2.CreateGameResponse
	(*JoinGameRequest)(nil),      // 8: gogame.v2.JoinGameRequest
	(*JoinGameResponse)(nil),     // 9: gogame.v2.JoinGameResponse
	(*StreamGamesRequest)(nil),   // 10: gogame.v2.StreamGamesRequest
	(*StreamGamesResponse)(nil),  // 11: gogame.v2.StreamGamesResponse
	(*StreamEventsRequest)(nil),  // 12: gogame.v2.StreamEventsRequest
	(*StreamEventsResponse)(nil), // 13: gogame.v2.StreamEventsResponse
	(*MoveRequest)(nil),          // 14: gogame.v2.MoveRequest
	(*MoveResponse)(nil),         // 15: gogame.v2.MoveResponse
	(*PassRequest)(nil),          // 16: gogame.v2.PassRequest
	(*PassResponse)(nil),         // 17: gogame.v2.PassResponse
	(*UndoRequest)(nil),          // 18: gogame.v2.UndoRequest
	(*UndoResponse)(nil),         // 19: gogame.v2.UndoResponse
	(*ResignRequest)(nil),        // 20: gogame.v2.ResignRequest
	(*ResignResponse)(nil),       // 21: gogame.v2.ResignResponse
	(*Change_Move)(nil),          // 22: gogame.v2.Change.Move
	(*Change_Pass)(nil),          // 23: gogame.v2.Change.Pass
	(*Change_Undo)(nil),          // 24: gogame.v2.Change.Undo
	(*Change_End)(nil),           // 25: gogame.v2.Change.End
}
var file_gogame_v2_server_proto_depIdxs = []int32{
	22, // 0: gogame.v2.Change.move:type_name -> gogame.v2.Change.Move
	23, // 1: gogame.v2.Change.pass:type_name -> gogame.v2.Change.Pass
	24, // 2: gogame.v2.Change.undo:type_name -> gogame.v2.Change.Undo
	25, // 3: gogame.v2.Change.end:type_name -> gogame.v2.Change.End
	1,  // 4: gogame.v2.Game.player1:type_name -> gogame.v2.Player
	1,  // 5: gogame.v2.Game.player2:type_name -> gogame.v2.Player
	2,  // 6: gogame.v2.Game.changes:type_name -> gogame.v2.Change
	5,  // 7: gogame.v2.Game.board:type_name -> gogame.v2.Board
	0,  // 8: gogame.v2.Row.colors:type_name -> gogame.v2.Color
	4,  // 9: gogame.v2.Board.rows:type_name -> gogame.v2.Row
	1,  // 10: gogame.v2.CreateGameRequest.player1:type_name -> gogame.v2.Player
	3,  // 11: gogame.v2.CreateGameResponse.game:type_name -> gogame.v2.Game
	1,  // 12: gogame.v2.JoinGameRequest.player2:type_name -> gogame.v2.Player
	3,  // 13: gogame.v2.JoinGameResponse.game:type_name -> gogame.v2.Game
	3,  // 14: gogame.v2.StreamGamesResponse.game:type_name -> gogame.v2.Game
	3,  // 15: gogame.v2.StreamEventsResponse.game:type_name -> gogame.v2.Game
	3,  // 16: gogame.v2.MoveResponse.game:type_name -> gogame.v2.Game
	3,  // 17: gogame.v2.PassResponse.game:type_name -> gogame.v2.Game
	3,  // 18: gogame.v2.UndoResponse.game:type_name -> gogame.v2.Game
	3,  // 19: gogame.v2.ResignResponse.game:type_name -> gogame.v2.Game
	0,  // 20: gogame.v2.Change.Move.color:type_name -> gogame.v2.Color
	1,  // 21: gogame.v2.Change.End.winner:type_name -> gogame.v2.Player
	6,  // 22: gogame.v2.RoomService.CreateGame:input_type -> gogame.v2.CreateGameRequest
	8,  // 23: gogame.v2.RoomService.JoinGame:input_type -> gogame.v2.JoinGameRequest
	10, // 24: gogame.v2.RoomService.StreamGames:input_type -> gogame.v2.StreamGamesRequest
	12, // 25: gogame.v2.GameService.StreamEvents:input_type -> gogame.v2.StreamEventsRequest
	14, // 26: gogame.v2.GameService.Move:input_type -> gogame.v2.MoveRequest
	20, // 27: gogame.v2.GameService.Resign:input_type -> gogame.v2.ResignRequest
	16, // 28: gogame.v2.GameService.Pass:input_type -> gogame.v2.PassRequest
	18, // 29: gogame.v2.GameService.Undo:input_type -> gogame.v2.UndoRequest
	7,  // 30: gogame.v2.RoomService.CreateGame:output_type -> gogame.v2.CreateGameResponse
	9,  // 31: gogame.v2.RoomService.JoinGame:output_type -> gogame.v2.JoinGameResponse
	11, // 32: gogame.v2.RoomService.StreamGames:output_type -> gogame.v2.StreamGamesResponse
	13, // 33: gogame.v2.GameService.StreamEvents:output_type -> gogame.v2.StreamEventsResponse
	15, // 34: gogame.v2.GameService.Move:output_type -> gogame.v2.MoveResponse
	21, // 35: gogame.v2.GameService.Resign:output_type -> gogame.v2.ResignResponse
	17, // 36: gogame.v2.GameService.Pass:output_type -> gogame.v2.PassResponse
	19, // 37: gogame.v2.GameService.Undo:output_type -> gogame.v2.UndoResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gogame_v2_server_proto_init() }
func file_gogame_v2_server_proto_init() {
	if File_gogame_v2_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gogame_v2_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Change); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*StreamGamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*StreamGamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*StreamEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StreamEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*PassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*PassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UndoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UndoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ResignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ResignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Change_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*Change_Pass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*Change_Undo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v2_server_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*Change_End); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gogame_v2_server_proto_msgTypes[1].OneofWrappers = []any{
		(*Change_Move_)(nil),
		(*Change_Pass_)(nil),
		(*Change_Undo_)(nil),
		(*Change_End_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gogame_v2_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gogame_v2_server_proto_goTypes,
		DependencyIndexes: file_gogame_v2_server_proto_depIdxs,
		EnumInfos:         file_gogame_v2_server_proto_enumTypes,
		MessageInfos:      file_gogame_v2_server_proto_msgTypes,
	}.Build()
	File_gogame_v2_server_proto = out.File
	file_gogame_v2_server_proto_rawDesc = nil
	file_gogame_v2_server_proto_goTypes = nil
	file_gogame_v2_server_proto_depIdxs = nil
}
