// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: gogame/v1/server.proto

package gogamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_BLACK       Color = 1
	Color_COLOR_WHITE       Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_BLACK",
		2: "COLOR_WHITE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_BLACK":       1,
		"COLOR_WHITE":       2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_gogame_v1_server_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_gogame_v1_server_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_CREATED     State = 1
	State_STATE_STARTED     State = 2
	State_STATE_MOVE        State = 3
	State_STATE_ENDED       State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_CREATED",
		2: "STATE_STARTED",
		3: "STATE_MOVE",
		4: "STATE_ENDED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_CREATED":     1,
		"STATE_STARTED":     2,
		"STATE_MOVE":        3,
		"STATE_ENDED":       4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_gogame_v1_server_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_gogame_v1_server_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{1}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CapturedStones int32  `protobuf:"varint,3,opt,name=captured_stones,json=capturedStones,proto3" json:"captured_stones,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetCapturedStones() int32 {
	if x != nil {
		return x.CapturedStones
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// current move
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color    Color  `protobuf:"varint,2,opt,name=color,proto3,enum=gogame.v1.Color" json:"color,omitempty"`
	EndAt    int64  `protobuf:"varint,7,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	// make move
	X int32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	// pass set by server for history
	Pass bool `protobuf:"varint,5,opt,name=pass,proto3" json:"pass,omitempty"`
	// undone set by server when undo is accepted
	Undone bool `protobuf:"varint,6,opt,name=undone,proto3" json:"undone,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Move) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Move) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Move) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *Move) GetUndone() bool {
	if x != nil {
		return x.Undone
	}
	return false
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// created
	Id              string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rev             int32   `protobuf:"varint,2,opt,name=rev,proto3" json:"rev,omitempty"`
	Name            string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Player1         *Player `protobuf:"bytes,4,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2         *Player `protobuf:"bytes,5,opt,name=player2,proto3" json:"player2,omitempty"`
	State           State   `protobuf:"varint,6,opt,name=state,proto3,enum=gogame.v1.State" json:"state,omitempty"`
	MoveDurationSec int32   `protobuf:"varint,12,opt,name=move_duration_sec,json=moveDurationSec,proto3" json:"move_duration_sec,omitempty"`
	// started
	CurrentMove   *Move   `protobuf:"bytes,7,opt,name=current_move,json=currentMove,proto3" json:"current_move,omitempty"`
	PreviousMoves []*Move `protobuf:"bytes,8,rep,name=previous_moves,json=previousMoves,proto3" json:"previous_moves,omitempty"`
	Board         *Board  `protobuf:"bytes,11,opt,name=board,proto3" json:"board,omitempty"`
	// ended
	Winner *Player `protobuf:"bytes,9,opt,name=winner,proto3" json:"winner,omitempty"`
	WonBy  string  `protobuf:"bytes,10,opt,name=won_by,json=wonBy,proto3" json:"won_by,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetRev() int32 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *Game) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *Game) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Game) GetMoveDurationSec() int32 {
	if x != nil {
		return x.MoveDurationSec
	}
	return 0
}

func (x *Game) GetCurrentMove() *Move {
	if x != nil {
		return x.CurrentMove
	}
	return nil
}

func (x *Game) GetPreviousMoves() []*Move {
	if x != nil {
		return x.PreviousMoves
	}
	return nil
}

func (x *Game) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Game) GetWinner() *Player {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *Game) GetWonBy() string {
	if x != nil {
		return x.WonBy
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colors []Color `protobuf:"varint,1,rep,packed,name=colors,proto3,enum=gogame.v1.Color" json:"colors,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Rows []*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *Board) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Board) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Player1 *Player `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type JoinGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string  `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Player2 *Player `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinGameRequest) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

type JoinGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *JoinGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type StreamVacantGamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamVacantGamesRequest) Reset() {
	*x = StreamVacantGamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamVacantGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVacantGamesRequest) ProtoMessage() {}

func (x *StreamVacantGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVacantGamesRequest.ProtoReflect.Descriptor instead.
func (*StreamVacantGamesRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{9}
}

type StreamVacantGamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *StreamVacantGamesResponse) Reset() {
	*x = StreamVacantGamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamVacantGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVacantGamesResponse) ProtoMessage() {}

func (x *StreamVacantGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVacantGamesResponse.ProtoReflect.Descriptor instead.
func (*StreamVacantGamesResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *StreamVacantGamesResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type StreamGameEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *StreamGameEventsRequest) Reset() {
	*x = StreamGameEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamGameEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGameEventsRequest) ProtoMessage() {}

func (x *StreamGameEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGameEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamGameEventsRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *StreamGameEventsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type StreamGameEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Undo *Undo `protobuf:"bytes,2,opt,name=undo,proto3" json:"undo,omitempty"`
}

func (x *StreamGameEventsResponse) Reset() {
	*x = StreamGameEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamGameEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGameEventsResponse) ProtoMessage() {}

func (x *StreamGameEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGameEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamGameEventsResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *StreamGameEventsResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *StreamGameEventsResponse) GetUndo() *Undo {
	if x != nil {
		return x.Undo
	}
	return nil
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	Move    *Move  `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *MakeMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMoveRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *MakeMoveRequest) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *MakeMoveResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type PassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev  int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *PassRequest) Reset() {
	*x = PassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRequest) ProtoMessage() {}

func (x *PassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRequest.ProtoReflect.Descriptor instead.
func (*PassRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *PassRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PassRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *PassRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *PassResponse) Reset() {
	*x = PassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassResponse) ProtoMessage() {}

func (x *PassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassResponse.ProtoReflect.Descriptor instead.
func (*PassResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *PassResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ResignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *ResignRequest) Reset() {
	*x = ResignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignRequest) ProtoMessage() {}

func (x *ResignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignRequest.ProtoReflect.Descriptor instead.
func (*ResignRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{17}
}

func (x *ResignRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ResignRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ResignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *ResignResponse) Reset() {
	*x = ResignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignResponse) ProtoMessage() {}

func (x *ResignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignResponse.ProtoReflect.Descriptor instead.
func (*ResignResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{18}
}

func (x *ResignResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type Undo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev  int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Move     int32  `protobuf:"varint,4,opt,name=move,proto3" json:"move,omitempty"`
	Decided  bool   `protobuf:"varint,5,opt,name=decided,proto3" json:"decided,omitempty"`
	Accepted bool   `protobuf:"varint,6,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *Undo) Reset() {
	*x = Undo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Undo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Undo) ProtoMessage() {}

func (x *Undo) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Undo.ProtoReflect.Descriptor instead.
func (*Undo) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{19}
}

func (x *Undo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Undo) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (x *Undo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Undo) GetMove() int32 {
	if x != nil {
		return x.Move
	}
	return 0
}

func (x *Undo) GetDecided() bool {
	if x != nil {
		return x.Decided
	}
	return false
}

func (x *Undo) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type UndoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRev int32  `protobuf:"varint,2,opt,name=game_rev,json=gameRev,proto3" json:"game_rev,omitempty"`
	// Types that are assignable to Action:
	//
	//	*UndoRequest_Request_
	//	*UndoRequest_Decision_
	Action isUndoRequest_Action `protobuf_oneof:"action"`
}

func (x *UndoRequest) Reset() {
	*x = UndoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRequest) ProtoMessage() {}

func (x *UndoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRequest.ProtoReflect.Descriptor instead.
func (*UndoRequest) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{20}
}

func (x *UndoRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UndoRequest) GetGameRev() int32 {
	if x != nil {
		return x.GameRev
	}
	return 0
}

func (m *UndoRequest) GetAction() isUndoRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *UndoRequest) GetRequest() *UndoRequest_Request {
	if x, ok := x.GetAction().(*UndoRequest_Request_); ok {
		return x.Request
	}
	return nil
}

func (x *UndoRequest) GetDecision() *UndoRequest_Decision {
	if x, ok := x.GetAction().(*UndoRequest_Decision_); ok {
		return x.Decision
	}
	return nil
}

type isUndoRequest_Action interface {
	isUndoRequest_Action()
}

type UndoRequest_Request_ struct {
	Request *UndoRequest_Request `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

type UndoRequest_Decision_ struct {
	Decision *UndoRequest_Decision `protobuf:"bytes,4,opt,name=decision,proto3,oneof"`
}

func (*UndoRequest_Request_) isUndoRequest_Action() {}

func (*UndoRequest_Decision_) isUndoRequest_Action() {}

type UndoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Undo *Undo `protobuf:"bytes,2,opt,name=undo,proto3" json:"undo,omitempty"`
}

func (x *UndoResponse) Reset() {
	*x = UndoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoResponse) ProtoMessage() {}

func (x *UndoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoResponse.ProtoReflect.Descriptor instead.
func (*UndoResponse) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{21}
}

func (x *UndoResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *UndoResponse) GetUndo() *Undo {
	if x != nil {
		return x.Undo
	}
	return nil
}

type UndoRequest_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *UndoRequest_Request) Reset() {
	*x = UndoRequest_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRequest_Request) ProtoMessage() {}

func (x *UndoRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRequest_Request.ProtoReflect.Descriptor instead.
func (*UndoRequest_Request) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{20, 0}
}

func (x *UndoRequest_Request) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type UndoRequest_Decision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted bool   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *UndoRequest_Decision) Reset() {
	*x = UndoRequest_Decision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogame_v1_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoRequest_Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRequest_Decision) ProtoMessage() {}

func (x *UndoRequest_Decision) ProtoReflect() protoreflect.Message {
	mi := &file_gogame_v1_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRequest_Decision.ProtoReflect.Descriptor instead.
func (*UndoRequest_Decision) Descriptor() ([]byte, []int) {
	return file_gogame_v1_server_proto_rawDescGZIP(), []int{20, 1}
}

func (x *UndoRequest_Decision) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UndoRequest_Decision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_gogame_v1_server_proto protoreflect.FileDescriptor

var file_gogame_v1_server_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x55, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0xaa, 0x01, 0x0a, 0x04, 0x4d,
	0x6f, 0x76, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0xc0, 0x03, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x65, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x31, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
	0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x63, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x6f, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x36, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x6f, 0x75, 0x73, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x77, 0x6f, 0x6e, 0x5f, 0x62, 0x79, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x6e, 0x42, 0x79, 0x22, 0x2f, 0x0a, 0x03, 0x52, 0x6f,
	0x77, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x22, 0x3f, 0x0a, 0x05, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x54, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x31, 0x22, 0x39, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a,
	0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x22, 0x37, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22,
	0x1a, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x19, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a,
	0x17, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x64, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64,
	0x6f, 0x52, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x22, 0x6a, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12, 0x23,
	0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d,
	0x6f, 0x76, 0x65, 0x22, 0x37, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0b,
	0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0c,
	0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d,
	0x65, 0x22, 0x45, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22,
	0xa1, 0x01, 0x0a, 0x04, 0x55, 0x6e, 0x64, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x64, 0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x22, 0xb3, 0x02, 0x0a, 0x0b, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x1a, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x43, 0x0a, 0x08, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x42,
	0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x0c, 0x55, 0x6e, 0x64,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x04, 0x75,
	0x6e, 0x64, 0x6f, 0x2a, 0x40, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x11,
	0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x41,
	0x43, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x57, 0x48,
	0x49, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x65, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15,
	0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x04, 0x32, 0xe4, 0x04, 0x0a,
	0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x23,
	0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a,
	0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61,
	0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67,
	0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76,
	0x65, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x04, 0x50, 0x61, 0x73, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x55, 0x6e, 0x64, 0x6f,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x98, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x61, 0x6b, 0x61, 0x73, 0x69, 0x6d, 0x2f, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x67, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x47, 0x58,
	0x58, 0xaa, 0x02, 0x09, 0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09,
	0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x47, 0x6f, 0x67, 0x61,
	0x6d, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0a, 0x47, 0x6f, 0x67, 0x61, 0x6d, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gogame_v1_server_proto_rawDescOnce sync.Once
	file_gogame_v1_server_proto_rawDescData = file_gogame_v1_server_proto_rawDesc
)

func file_gogame_v1_server_proto_rawDescGZIP() []byte {
	file_gogame_v1_server_proto_rawDescOnce.Do(func() {
		file_gogame_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_gogame_v1_server_proto_rawDescData)
	})
	return file_gogame_v1_server_proto_rawDescData
}

var file_gogame_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gogame_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gogame_v1_server_proto_goTypes = []any{
	(Color)(0),                        // 0: gogame.v1.Color
	(State)(0),                        // 1: gogame.v1.State
	(*Player)(nil),                    // 2: gogame.v1.Player
	(*Move)(nil),                      // 3: gogame.v1.Move
	(*Game)(nil),                      // 4: gogame.v1.Game
	(*Row)(nil),                       // 5: gogame.v1.Row
	(*Board)(nil),                     // 6: gogame.v1.Board
	(*CreateGameRequest)(nil),         // 7: gogame.v1.CreateGameRequest
	(*CreateGameResponse)(nil),        // 8: gogame.v1.CreateGameResponse
	(*JoinGameRequest)(nil),           // 9: gogame.v1.JoinGameRequest
	(*JoinGameResponse)(nil),          // 10: gogame.v1.JoinGameResponse
	(*StreamVacantGamesRequest)(nil),  // 11: gogame.v1.StreamVacantGamesRequest
	(*StreamVacantGamesResponse)(nil), // 12: gogame.v1.StreamVacantGamesResponse
	(*StreamGameEventsRequest)(nil),   // 13: gogame.v1.StreamGameEventsRequest
	(*StreamGameEventsResponse)(nil),  // 14: gogame.v1.StreamGameEventsResponse
	(*MakeMoveRequest)(nil),           // 15: gogame.v1.MakeMoveRequest
	(*MakeMoveResponse)(nil),          // 16: gogame.v1.MakeMoveResponse
	(*PassRequest)(nil),               // 17: gogame.v1.PassRequest
	(*PassResponse)(nil),              // 18: gogame.v1.PassResponse
	(*ResignRequest)(nil),             // 19: gogame.v1.ResignRequest
	(*ResignResponse)(nil),            // 20: gogame.v1.ResignResponse
	(*Undo)(nil),                      // 21: gogame.v1.Undo
	(*UndoRequest)(nil),               // 22: gogame.v1.UndoRequest
	(*UndoResponse)(nil),              // 23: gogame.v1.UndoResponse
	(*UndoRequest_Request)(nil),       // 24: gogame.v1.UndoRequest.Request
	(*UndoRequest_Decision)(nil),      // 25: gogame.v1.UndoRequest.Decision
}
var file_gogame_v1_server_proto_depIdxs = []int32{
	0,  // 0: gogame.v1.Move.color:type_name -> gogame.v1.Color
	2,  // 1: gogame.v1.Game.player1:type_name -> gogame.v1.Player
	2,  // 2: gogame.v1.Game.player2:type_name -> gogame.v1.Player
	1,  // 3: gogame.v1.Game.state:type_name -> gogame.v1.State
	3,  // 4: gogame.v1.Game.current_move:type_name -> gogame.v1.Move
	3,  // 5: gogame.v1.Game.previous_moves:type_name -> gogame.v1.Move
	6,  // 6: gogame.v1.Game.board:type_name -> gogame.v1.Board
	2,  // 7: gogame.v1.Game.winner:type_name -> gogame.v1.Player
	0,  // 8: gogame.v1.Row.colors:type_name -> gogame.v1.Color
	5,  // 9: gogame.v1.Board.rows:type_name -> gogame.v1.Row
	2,  // 10: gogame.v1.CreateGameRequest.player1:type_name -> gogame.v1.Player
	4,  // 11: gogame.v1.CreateGameResponse.game:type_name -> gogame.v1.Game
	2,  // 12: gogame.v1.JoinGameRequest.player2:type_name -> gogame.v1.Player
	4,  // 13: gogame.v1.JoinGameResponse.game:type_name -> gogame.v1.Game
	4,  // 14: gogame.v1.StreamVacantGamesResponse.game:type_name -> gogame.v1.Game
	4,  // 15: gogame.v1.StreamGameEventsResponse.game:type_name -> gogame.v1.Game
	21, // 16: gogame.v1.StreamGameEventsResponse.undo:type_name -> gogame.v1.Undo
	3,  // 17: gogame.v1.MakeMoveRequest.move:type_name -> gogame.v1.Move
	4,  // 18: gogame.v1.MakeMoveResponse.game:type_name -> gogame.v1.Game
	4,  // 19: gogame.v1.PassResponse.game:type_name -> gogame.v1.Game
	4,  // 20: gogame.v1.ResignResponse.game:type_name -> gogame.v1.Game
	24, // 21: gogame.v1.UndoRequest.request:type_name -> gogame.v1.UndoRequest.Request
	25, // 22: gogame.v1.UndoRequest.decision:type_name -> gogame.v1.UndoRequest.Decision
	4,  // 23: gogame.v1.UndoResponse.game:type_name -> gogame.v1.Game
	21, // 24: gogame.v1.UndoResponse.undo:type_name -> gogame.v1.Undo
	7,  // 25: gogame.v1.GameService.CreateGame:input_type -> gogame.v1.CreateGameRequest
	11, // 26: gogame.v1.GameService.StreamVacantGames:input_type -> gogame.v1.StreamVacantGamesRequest
	9,  // 27: gogame.v1.GameService.JoinGame:input_type -> gogame.v1.JoinGameRequest
	13, // 28: gogame.v1.GameService.StreamGameEvents:input_type -> gogame.v1.StreamGameEventsRequest
	15, // 29: gogame.v1.GameService.MakeMove:input_type -> gogame.v1.MakeMoveRequest
	19, // 30: gogame.v1.GameService.Resign:input_type -> gogame.v1.ResignRequest
	17, // 31: gogame.v1.GameService.Pass:input_type -> gogame.v1.PassRequest
	22, // 32: gogame.v1.GameService.Undo:input_type -> gogame.v1.UndoRequest
	8,  // 33: gogame.v1.GameService.CreateGame:output_type -> gogame.v1.CreateGameResponse
	12, // 34: gogame.v1.GameService.StreamVacantGames:output_type -> gogame.v1.StreamVacantGamesResponse
	10, // 35: gogame.v1.GameService.JoinGame:output_type -> gogame.v1.JoinGameResponse
	14, // 36: gogame.v1.GameService.StreamGameEvents:output_type -> gogame.v1.StreamGameEventsResponse
	16, // 37: gogame.v1.GameService.MakeMove:output_type -> gogame.v1.MakeMoveResponse
	20, // 38: gogame.v1.GameService.Resign:output_type -> gogame.v1.ResignResponse
	18, // 39: gogame.v1.GameService.Pass:output_type -> gogame.v1.PassResponse
	23, // 40: gogame.v1.GameService.Undo:output_type -> gogame.v1.UndoResponse
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_gogame_v1_server_proto_init() }
func file_gogame_v1_server_proto_init() {
	if File_gogame_v1_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gogame_v1_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*StreamVacantGamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*StreamVacantGamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*StreamGameEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StreamGameEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*MakeMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*MakeMoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*PassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*PassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ResignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ResignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Undo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*UndoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UndoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*UndoRequest_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogame_v1_server_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*UndoRequest_Decision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gogame_v1_server_proto_msgTypes[20].OneofWrappers = []any{
		(*UndoRequest_Request_)(nil),
		(*UndoRequest_Decision_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gogame_v1_server_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gogame_v1_server_proto_goTypes,
		DependencyIndexes: file_gogame_v1_server_proto_depIdxs,
		EnumInfos:         file_gogame_v1_server_proto_enumTypes,
		MessageInfos:      file_gogame_v1_server_proto_msgTypes,
	}.Build()
	File_gogame_v1_server_proto = out.File
	file_gogame_v1_server_proto_rawDesc = nil
	file_gogame_v1_server_proto_goTypes = nil
	file_gogame_v1_server_proto_depIdxs = nil
}
